# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'RTLSSensor', :git => 'https://github.com/coreaiot/RTLSSensor.git', :tag => '1.0.0'
target 'AOATestOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AOATestOC

end
