# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wcdbTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
pod 'WCDB.swift'
pod 'WCDB'
pod 'IndoorMapFramework', '0.36.1'

  # Pods for wcdbTest

end
