# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#每个sdk和工程都要用的放这里:
pod 'iConsole',    '~> 1.5.3'
pod 'MTDates', '~> 1.0.3'
pod 'Toast', '~> 4.0.0'
pod 'YYModel', '1.0.4'

target 'HTMCommonTest' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for HTMCommonTest

end
